# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: Practical coding
#title: 학습하고 적용하고 공유하자
title: Likelion-DGIST 기술블로그
email: taehyeongkim@likelion.org
description: >- # this means to ignore newlines until "baseurl:"
  Likelion-DGIST 기술블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://likelion-dgist.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username: likelion-dgist
tistory_username : likelion-dgist
twitter_username: likelion-dgist
twitter_username2: likelion-dgist
facebook_username:  likelion-dgist
google_analytics: False

disqus:
  comments: true
  shortname: min9nim


# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-whiteglass
asset_url: /assets
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

port : 4000
host : 0.0.0.0

permalink: /:year/:month/:title/
paginate_path: /posts/:num/
paginate: 5

navigation:
 - title: About
   url: /about
 - title: Category
   url: /category
 - title: Tags
   url: /tags
 - title: Archives
   url: /archives


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
